### ISSUE TITLE
I got the following errors when I try to running the ssd300.py

### ISSUE THREAD

**Issue by tianxianhao** [open-mmlab/mmdetection#4513]
TypeError: __init__() got an unexpected keyword argument '_delete_'
Traceback (most recent call last):
  File "../mmdetection/tools/train.py", line 187, in <module>
    main()
  File "../mmdetection/tools/train.py", line 183, in main
    meta=meta)
  File "/home/tianxianhao/Project/mmdet/mmdetection/mmdet/apis/train.py", line 102, in train_detector
    optimizer_config = OptimizerHook(**cfg.optimizer_config)
TypeError: __init__() got an unexpected keyword argument '_delete_'

**Comment by tianxianhao** [comment]
Besides, I cannot load the resume .pth file when training to fine-tune the model after i update the mmdetection version to 2.8.0+. I have update mmcv and install other requirement.

**Comment by tianxianhao** [comment]
And if i do not use the setting of "resume = None", the training can running normally.

**Comment by tianxianhao** [comment]
I have solved this problem about the resume  model cannot finetune.
The total epoch should be larger than the resumed epoch. Otherwise, the runner cannot work and exit the progress directly without any warning.  Please add the notice in the future version. 
mmdet 2.6 has much difference compared with 2.8. It bring much problem to me. I will close this issue.
