### ISSUE TITLE
./compile.sh compile ERROR

### ISSUE THREAD

**Issue by heshuting555** [open-mmlab/mmdetection#789]
Building roi align op...
running build_ext
building 'roi_align_cuda' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /root/anaconda3/envs/mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include/TH -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/root/anaconda3/envs/mmlab/include/python3.6m -c src/roi_align_cuda.cpp -o build/temp.linux-x86_64-3.6/src/roi_align_cuda.o -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
src/roi_align_cuda.cpp:1:29: fatal error: torch/extension.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
Building roi pool op...
running build_ext
building 'roi_pool_cuda' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /root/anaconda3/envs/mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include/TH -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/root/anaconda3/envs/mmlab/include/python3.6m -c src/roi_pool_cuda.cpp -o build/temp.linux-x86_64-3.6/src/roi_pool_cuda.o -DTORCH_EXTENSION_NAME=roi_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
src/roi_pool_cuda.cpp:1:29: fatal error: torch/extension.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
Building nms op...
running build_ext
running build_ext
building 'nms_cuda' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /root/anaconda3/envs/mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include/TH -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/root/anaconda3/envs/mmlab/include/python3.6m -c src/nms_cuda.cpp -o build/temp.linux-x86_64-3.6/src/nms_cuda.o -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
src/nms_cuda.cpp:2:29: fatal error: torch/extension.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
Building dcn...
running build_ext
building 'deform_conv_cuda' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /root/anaconda3/envs/mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include/TH -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/root/anaconda3/envs/mmlab/include/python3.6m -c src/deform_conv_cuda.cpp -o build/temp.linux-x86_64-3.6/src/deform_conv_cuda.o -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
src/deform_conv_cuda.cpp:4:29: fatal error: torch/extension.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
Building sigmoid focal loss op...
running build_ext
building 'sigmoid_focal_loss_cuda' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /root/anaconda3/envs/mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include/TH -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/root/anaconda3/envs/mmlab/include/python3.6m -c src/sigmoid_focal_loss.cpp -o build/temp.linux-x86_64-3.6/src/sigmoid_focal_loss.o -DTORCH_EXTENSION_NAME=sigmoid_focal_loss_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
src/sigmoid_focal_loss.cpp:3:29: fatal error: torch/extension.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
Building masked conv op...
running build_ext
building 'masked_conv2d_cuda' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /root/anaconda3/envs/mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include/TH -I/root/anaconda3/envs/mmlab/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/root/anaconda3/envs/mmlab/include/python3.6m -c src/masked_conv2d_cuda.cpp -o build/temp.linux-x86_64-3.6/src/masked_conv2d_cuda.o -DTORCH_EXTENSION_NAME=masked_conv2d_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
src/masked_conv2d_cuda.cpp:1:29: fatal error: torch/extension.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
############################################################################
Can you help me. I cannot found a solution that is similar to my mistake. “fatal error: torch/extension.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1” is repeated many times.
###########################################################################
My environment:
pytorch 0.4.1
gcc  5.4.0
cuda 9.0
cudnn 7.1.2
torchvision 0.2.1
cuda PATH:
export PATH=/usr/local/cuda-9.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH

Thank you for your help. I have been crashed by mistake

**Comment by hellock** [comment]
Please refer to the readme.
>The master branch works with PyTorch 1.1 or higher.

**Comment by heshuting555** [comment]
Thank you for your help.




------------------ 原始邮件 ------------------
发件人: "Kai Chen"<notifications@github.com>;
发送时间: 2019年6月14日(星期五) 凌晨1:21
收件人: "open-mmlab/mmdetection"<mmdetection@noreply.github.com>;
抄送: "浮城﹋"<1173718914@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [open-mmlab/mmdetection] ./compile.sh compile ERROR (#789)




Please refer to the readme.
  
The master branch works with PyTorch 1.1 or higher.
