### ISSUE TITLE
'SSDHead' object has no attribute 'loss_cls'

### ISSUE THREAD

**Issue by beratatmaca** [open-mmlab/mmdetection#11780]
When I upgraded MMDet to 3.3.0, I receive the following error message while training my model. My model was working fine with the previous MMDet version (v3.0.0)

`AttributeError: 'SSDHead' object has no attribute 'loss_cls'`

I think the error raised [here](https://github.com/open-mmlab/mmdetection/blob/fe3f809a0a514189baf889aa358c498d51ee36cd/mmdet/models/dense_heads/base_dense_head.py#L376) because it tries to access `loss_cls` object that is never created. 

I think the error happens during validation loss computation.  `self.loss_cls` object is created [here](https://github.com/open-mmlab/mmdetection/blob/fe3f809a0a514189baf889aa358c498d51ee36cd/mmdet/models/dense_heads/anchor_head.py#L84), but the SSDHead does not initialize its parent class. It initializes the super-parent class directly [here](https://github.com/open-mmlab/mmdetection/blob/fe3f809a0a514189baf889aa358c498d51ee36cd/mmdet/models/dense_heads/ssd_head.py#L85).

So what probably happened is that when a new detector support was introduced in [this commit](https://github.com/open-mmlab/mmdetection/commit/6f85dfeb045faebda918fdc6fcc7625c41e0f4c2#diff-8e8b02a5e30fd4d2784369602102a57fed27cb51f27c94d87139294181a286f5), it was assumed that every sub/superclass has self.loss_cls defined. However for SSD this is not the case.

**Comment by onlylrs** [comment]
Adding `self.loss_cls = nn.CrossEntropyLoss(reduction='none')` at https://github.com/open-mmlab/mmdetection/blob/main/mmdet/models/dense_heads/ssd_head.py line 108 solved the problem. For reference.
